# Generated by Django 3.1.5 on 2021-01-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcode',
            old_name='short_url',
            new_name='shortcode',
        ),
    ]
