# Generated by Django 3.1.5 on 2021-01-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0002_auto_20210115_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcode',
            old_name='shortcode',
            new_name='short_url',
        ),
    ]
