# Generated by Django 3.1.5 on 2021-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0003_auto_20210115_1141'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shortcode',
            constraint=models.CheckConstraint(check=models.Q(short_url__length__gte=4), name='shortcode_shortcode_short_url_lentgh'),
        ),
    ]
